spring.application.name=robot-kanban-service
server.port=9987
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
teaql.ensureTable=true
teaql.contextClass=com.doublechaintech.robotkanbanservice.CustomUserContext

spring.datasource.username=
spring.datasource.password=
spring.datasource.url=jdbc:sqlite:../robot_kanban.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.data.redis.port=6379
plc.deploy.url=
card.service.url=
aliyun.sms.ak=
aliyun.sms.sk=logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
